[build]
builder = "nixpacks"

[deploy]
# TEMPORARY: create_superadmin will create 2 admin users (remove this after deployment!)
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py create_superadmin && gunicorn smartspaceupy.wsgi"
